export const COMMUNICATE_TV = [
  { id: 1, name: 'ПЕРВЫЙ КАНАЛ', rating: 31, logo: 'https://ssp.rmh.ru/tibco/minec/logos/tv/ПЕРВЫЙ%20КАНАЛ.png' },
  { id: 2, name: 'РОССИЯ 1', rating: 23, logo: 'https://ssp.rmh.ru/tibco/minec/logos/tv/РОССИЯ%201.png' },
  { id: 3, name: 'РЕН ТВ', rating: 22, logo: 'https://ssp.rmh.ru/tibco/minec/logos/tv/РЕН%20ТВ.png' },
  { id: 4, name: 'СТС', rating: 21, logo: 'https://ssp.rmh.ru/tibco/minec/logos/tv/СТС.png' },
  { id: 5, name: 'ТНТ', rating: 19, logo: 'https://ssp.rmh.ru/tibco/minec/logos/tv/ТНТ.png' },
  { id: 6, name: 'ПЯТНИЦА', rating: 19, logo: 'https://ssp.rmh.ru/tibco/minec/logos/tv/ПЯТНИЦА.png' },
  { id: 7, name: 'НТВ', rating: 16, logo: 'https://ssp.rmh.ru/tibco/minec/logos/tv/НТВ.png' },
  { id: 8, name: 'РОССИЯ 24', rating: 16, logo: 'https://ssp.rmh.ru/tibco/minec/logos/tv/РОССИЯ%2024.png' },
  { id: 9, name: 'ТВ-3', rating: 15, logo: 'https://ssp.rmh.ru/tibco/minec/logos/tv/ТВ-3.png' },
  { id: 10, name: 'ПЯТЫЙ КАНАЛ', rating: 15, logo: 'https://ssp.rmh.ru/tibco/minec/logos/tv/ПЯТЫЙ%20КАНАЛ.png' },
  { id: 11, name: 'МАТЧ ТВ', rating: 14, logo: 'https://ssp.rmh.ru/tibco/minec/logos/tv/МАТЧ%20ТВ.png' },
  { id: 12, name: 'Ю', rating: 13, logo: 'https://ssp.rmh.ru/tibco/minec/logos/tv/Ю.png' },
  { id: 13, name: 'МУЗ ТВ', rating: 13, logo: 'https://ssp.rmh.ru/tibco/minec/logos/tv/МУЗ%20ТВ.png' },
  { id: 14, name: 'КАРУСЕЛЬ', rating: 12, logo: 'https://ssp.rmh.ru/tibco/minec/logos/tv/КАРУСЕЛЬ.png' },
  { id: 15, name: 'ЗВЕЗДА', rating: 10, logo: 'https://ssp.rmh.ru/tibco/minec/logos/tv/ЗВЕЗДА.png' },
  { id: 16, name: 'ЧЕ', rating: 9, logo: 'https://ssp.rmh.ru/tibco/minec/logos/tv/ЧЕ.png' },
  { id: 17, name: 'ДОМАШНИЙ', rating: 9, logo: 'https://ssp.rmh.ru/tibco/minec/logos/tv/ДОМАШНИЙ.png' },
  { id: 18, name: 'ТВ ЦЕНТР', rating: 8, logo: 'https://ssp.rmh.ru/tibco/minec/logos/tv/ТВ%20ЦЕНТР.png' },
  { id: 20, name: 'СТС LOVE', rating: 4, logo: 'https://ssp.rmh.ru/tibco/minec/logos/tv/СТС%20LOVE.png' },
];

export const COMMUNICATE_SITE = [
  { id: 21, name: 'Yandex Поиск', rating: 28, logo: 'https://ssp.rmh.ru/tibco/minec/mobile_appl/Яндекс.png' },
  { id: 22, name: 'vk.com', rating: 18, logo: 'https://ssp.rmh.ru/tibco/minec/mobile_appl/ВКонтакте.png' },
  { id: 23, name: 'Mail Почта', rating: 18, logo: 'https://ssp.rmh.ru/tibco/minec/mobile_appl/Почта%20Mail.Ru.png' },
  { id: 24, name: 'Mail Поиск', rating: 17, logo: 'https://ssp.rmh.ru/tibco/minec/mobile_appl/Почта%20Mail.Ru.png' },
  { id: 25, name: 'YouTube.com', rating: 15, logo: 'https://ssp.rmh.ru/tibco/minec/mobile_appl/YouTube.png' },
  { id: 26, name: 'Yandex Почта', rating: 14, logo: 'https://ssp.rmh.ru/tibco/minec/mobile_appl/Яндекс.Почта.png' },
  { id: 27, name: 'Google Поиск', rating: 13, logo: 'https://ssp.rmh.ru/tibco/minec/mobile_appl/Google.png' },
  { id: 28, name: 'gosuslugi.ru', rating: 9, logo: 'https://ssp.rmh.ru/tibco/minec/mobile_appl/Госуслуги.png' },
  { id: 29, name: 'Mail Новости', rating: 7, logo: 'https://ssp.rmh.ru/tibco/minec/mobile_appl/Почта%20Mail.Ru.png' },
  { id: 30, name: 'Yandex Дзен', rating: 7, logo: 'https://ssp.rmh.ru/tibco/minec/mobile_appl/Яндекс.png' },
  { id: 31, name: 'ok.ru', rating: 6, logo: 'https://ssp.rmh.ru/tibco/minec/mobile_appl/Одноклассники.png' },
  { id: 32, name: 'Yandex Маркет', rating: 5, logo: 'https://ssp.rmh.ru/tibco/minec/mobile_appl/Яндекс.png' },
  { id: 33, name: 'nalog.ru', rating: 5, logo: 'https://ssp.rmh.ru/tibco/minec/mobile_appl/Яндекс.png' },
  { id: 34, name: 'Yandex Погода', rating: 4, logo: 'https://ssp.rmh.ru/tibco/minec/mobile_appl/Яндекс.Погода.png' },
  { id: 35, name: 'Yandex Новости', rating: 3, logo: 'https://ssp.rmh.ru/tibco/minec/mobile_appl/Яндекс.png' }
];

export const COMMUNICATE_RADIO = [
  {id: 35, name: 'Европа Плюс', rating: 20, logo: '' },
  {id: 36, name: 'Русское радио', rating: 19, logo: '' },
  {id: 37, name: 'NRJ Radio', rating: 18, logo: '' },
  {id: 38, name: 'Новое радио', rating: 16, logo: '' },
  {id: 39, name: 'Love Radio', rating: 14, logo: '' },
  {id: 40, name: 'Хит FM', rating: 14, logo: '' },
  {id: 41, name: 'Ретро FM', rating: 13, logo: '' },
  {id: 42, name: 'DFM', rating: 12, logo: '' },
  {id: 43, name: 'Авторадио', rating: 11, logo: '' },
  {id: 44, name: 'Юмор-FM', rating: 11, logo: '' },
]

export const COMMUNICATE_POLITIC = [
  {id: 45, name: 'Путин', rating: 10.0 },
  {id: 46, name: 'Миронов', rating: 10.0 },
  {id: 47, name: 'Жириновский', rating: 2.0 },
  {id: 48, name: 'Лавров', rating: 3.0 },
  {id: 49, name: 'Шойгу', rating: 4.0 },
  {id: 51, name: 'Мишустин', rating: 5.0 },
  {id: 52, name: 'Медведев', rating: 6.0 },
  {id: 53, name: 'Собянин', rating: 7.0 },
  {id: 54, name: 'Песков', rating: 8.0 },
  {id: 55, name: 'Зюганов', rating: 9.0 },
]